/*
Identifies customers with high total balances.
Filters customers exceeding a balance threshold.
*/


SELECT
	CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS CUSTOMER_NAME,
	SUM(A.BALANCE) AS TOTAL_BALANCE
FROM
	CUSTOMERS C
	JOIN ACCOUNTS A ON C.CUSTOMER_ID = A.CUSTOMER_ID
GROUP BY
	C.FIRST_NAME,
	C.LAST_NAME
HAVING
	SUM(A.BALANCE) > 5000
ORDER BY
	TOTAL_BALANCE DESC