/*
Calculates loan repayment progress.
Shows total paid and remaining balance per loan.
*/


SELECT DISTINCT
	L.LOAN_ID,
	SUM(L.LOAN_AMOUNT) AS TOTAL_LOAN_AMOUNT,
	SUM(LP.PAYMENT_AMOUNT) AS TOTAL_PAID,
	SUM(L.LOAN_AMOUNT) - SUM(LP.PAYMENT_AMOUNT) AS REMAINING_BALANCE
FROM
	LOANS L
	JOIN LOAN_PAYMENTS LP ON L.LOAN_ID = LP.LOAN_ID
GROUP BY
	L.LOAN_ID