/*
Identifies top customers by total transaction amount.
Ranks customers based on transaction value.
*/


SELECT
	C.CUSTOMER_ID,
	CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS CUSTOMER_NAME,
	SUM(COALESCE(T.AMOUNT, 0)) AS TOTAL_TRANSACTION_AMOUNT
FROM
	CUSTOMERS C
	LEFT JOIN ACCOUNTS A ON C.CUSTOMER_ID = A.CUSTOMER_ID
	JOIN TRANSACTIONS T ON A.ACCOUNT_ID = T.ACCOUNT_ID
GROUP BY
	C.CUSTOMER_ID,
	C.FIRST_NAME,
	C.LAST_NAME
ORDER BY
	TOTAL_TRANSACTION_AMOUNT DESC
LIMIT
	3