/*
Provides high-level bank KPIs.
Includes customers, accounts, deposits, and loan exposure.
*/


WITH
	LOAN_EXPOSURE AS (
		SELECT
			L.CUSTOMER_ID,
			SUM(L.LOAN_AMOUNT) - SUM(LP.PAYMENT_AMOUNT) AS LOAN_EXPOSURE
		FROM
			LOANS L
			LEFT JOIN LOAN_PAYMENTS LP ON L.LOAN_ID = LP.LOAN_ID
		GROUP BY
			L.CUSTOMER_ID
	),
	DEPOSIT_STATS AS (
		SELECT
			A.CUSTOMER_ID,
			COUNT(DISTINCT T.TRANSACTION_ID) FILTER (
				WHERE
					T.TRANSACTION_TYPE = 'Deposit'
			) AS TOTAL_DEPOSITS
		FROM
			ACCOUNTS A
			LEFT JOIN TRANSACTIONS T ON A.ACCOUNT_ID = T.ACCOUNT_ID
		GROUP BY
			A.CUSTOMER_ID
	)
SELECT
	COUNT(DISTINCT C.CUSTOMER_ID) AS TOTAL_CUSTOMERS,
	COUNT(DISTINCT A.ACCOUNT_ID) AS TOTAL_ACCOUNTS,
	SUM(COALESCE(DS.TOTAL_DEPOSITS, 0)) AS TOTAL_DEPOSITS,
	SUM(COALESCE(LE.LOAN_EXPOSURE, 0)) AS LOAN_EXPOSURE
FROM
	CUSTOMERS C
	LEFT JOIN ACCOUNTS A ON C.CUSTOMER_ID = A.CUSTOMER_ID
	LEFT JOIN DEPOSIT_STATS DS ON C.CUSTOMER_ID = DS.CUSTOMER_ID
	LEFT JOIN LOAN_EXPOSURE LE ON C.CUSTOMER_ID = LE.CUSTOMER_ID